server:
  port: 80

spring:
  mail:
    host: smtp.163.com
    username: lamshiming@163.com
    password: qazwsx123456
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true