server:
  port: 80

management:
  security:
    enabled: false #关掉安全认证
  port: 80
  context-path: /shiming #actuator的访问路径
endpoints:
  shutdown:
    enabled: true #提供了使用post请求来关闭Spring Boot应用的功能。
  beans:
    id: instances


